# -*- coding: utf-8 -*-
"""Whisper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZvx_3m-654NFTRgXPKIVX4IVnzHQSrD
"""

path_name_ = '/content/SnapSave.io - How to sound smart in your TEDx Talk _ Will Stephen _ TEDxNewYork (128 kbps).mp3'

!pip install git+https://github.com/openai/whisper.git

import whisper
import numpy as np
def whiper_transcribe(path_name_):
  path_name = path_name_

  lang = "en"
  model_size = "small"
  model = whisper.load_model(model_size)
  audio = whisper.load_audio(path_name)

  result = model.transcribe(audio, verbose=False, temperature=0.8, language=lang,  condition_on_previous_text=True)

  # Write into a text file
  with open("output.txt", "w") as f:
    f.write("output.txt")
    f.write(result["text"])
  return result["text"]

def generate_input():
  output_text = whiper_transcribe(path_name_)
  split_sentence = output_text.split('.')
  input_list = []
  for i in range(3):
    #get randomly three sentences to have AI improve it
    input_list.append(split_sentence[np.random.randint(0, len(split_sentence))])
  return output_text, input_list

generate_input()