# Generated by Django 4.2.6 on 2023-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_recording_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
